p3dd:
  outputs:
    dev:
      dataset: silver
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dtc-de-0315
      threads: 1
      type: bigquery
  target: dev
