name: p3dd
version: 1.0.0
config-version: 2

source-paths:
  - "models"
  - "data"

target-path: "target"
clean-targets:
  - "target"

profile: "p3dd"

models:
  p3dd:
    jobs_growth:
      materialized: table
      schema: silver
    jobs_daily_total:
      materialized: view
      schema: gold
    jobs_daily_weekly_monthly_growth:
      materialized: view
      schema: gold