name: my_project_name
version: 1.0.0
config-version: 2

source-paths:
  - "models"
  - "data"

target-path: "target"
clean-targets:
  - "target"

profile: "p3dd"

models:
  p3dd:
    jobs_daily_total:
      +materialized: view
      +schema: silver
    jobs_daily_growth:
      +materialized: view
      +schema: silver
    jobs_weekly_growth:
      +materialized: view
      +schema: silver
    jobs_monthly_growth:
      +materialized: view
      +schema: silver

    sources:
      bronze:
        tables:
          - name: jobs
            description: "The daily number of job postings for each Financial Instrument Global Identifier (FIGI)."
          - name: figi
            description: "Financial Instrument Global Identifier (FIGI) information."
