version: 2

models:
  - name: jobs_daily_total
    description: "View to get the daily total number of jobs"
    columns:
      - name: day
        description: "The date for which the total number of jobs is calculated"
        tests:
          - not_null
      - name: total_num_jobs
        description: "The total number of jobs for the given date where the particular company has not previously had any days with total_num_jobs > 1000 to avoid accuracy errors"
        tests:
          - not_null
