project_id = "my-new-project"
billing_account = "my-billing-account"
gcs_bucket_name = "my-bucket-name"
region = "US"
bigquery_dataset_name = "my-bigquery-name"
service_account_name = "my-service-account-name"